### ISSUE TITLE
add topic fortran-tutorial

### ISSUE THREAD

**Issue by Beliavsky** [fortran-fans/Fortran-in-Action#31]
Looks good when I use Google translate :).

**Comment by zoziha** [comment]
In China, most of our paper book tutorials are content before the Fortran 2003 standard. The content of the Chinese tutorials on the Internet is relatively scattered, and there are some errors, and they are not modern enough. We are planning to write a preliminary Chinese tutorial for Chinese users. Hope It can go on for a long time.

Thanks @Beliavsky . The `fortran-tutorial` tag has been added.
